In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import tensorflow as tf
from tensorflow import keras
from keras import metrics

In [2]:
x_train = np.load('207_data/saved_data/x_train_square.npy')
y_train = np.load('207_data/saved_data/y_train_square.npy')

In [3]:
model = tf.keras.Sequential()

    # add first convolution layer to the model
model.add(tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_last',
    name='conv_1',
    activation='relu'))


    # add a max pooling layer with pool size (2,2) and strides of 2
    # (this will reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    name='pool_1'))


    # add second convolutional layer
model.add(tf.keras.layers.Conv2D(
    filters=64,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    name='conv_2',
    activation='relu'))

    # add second max pooling layer with pool size (2,2) and strides of 2
    # (this will further reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2), name='pool_2')
)


    # add a fully connected layer (need to flatten the output of the previous layers first)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(
    units=1024,
    name='fc_1',
    activation='relu'))

    # add dropout layer
model.add(tf.keras.layers.Dropout(
    rate=0.5))

    # add the last fully connected layer
    # this last layer sets the activation function to "None" in order to output the logits
    # note that passing activation = "sigmoid" will return class memembership probabilities but
    # in TensorFlow logits are prefered for numerical stability
    # set units=1 to get a single output unit (remember it's a binary classification problem)
model.add(tf.keras.layers.Dense(
    units=40000,
    name='fc_2',
    activation='relu'))

model.add(tf.keras.layers.Reshape((200, 200)))
    # build model and print summary
tf.random.set_seed(1)
model.build(input_shape=(None, 200, 200, 3))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv_1 (Conv2D)              (None, 200, 200, 32)      896
_________________________________________________________________
pool_1 (MaxPooling2D)        (None, 100, 100, 32)      0
_________________________________________________________________
conv_2 (Conv2D)              (None, 100, 100, 64)      18496
_________________________________________________________________
pool_2 (MaxPooling2D)        (None, 50, 50, 64)        0
_________________________________________________________________
flatten (Flatten)            (None, 160000)            0
_________________________________________________________________
fc_1 (Dense)                 (None, 1024)              163841024
_________________________________________________________________
dropout (Dropout)            (None, 1024)              0
_________________________________________________________________
fc_2 (Dense)                 (None, 40000)             41000000
_________________________________________________________________
reshape (Reshape)            (None, 200, 200)          0
=================================================================
Total params: 204,860,416
Trainable params: 204,860,416
Non-trainable params: 0
_________________________________________________________________

In [4]:
model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='mse')

In [5]:
%%time

history = model.fit(
  x = x_train,
  y = y_train,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 10,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
315/315 [==============================] - 321s 1s/step - loss: 12961.5529 - val_loss: 1099.0018
Epoch 2/10
315/315 [==============================] - 316s 1s/step - loss: 1440.3084 - val_loss: 1079.0994
Epoch 3/10
315/315 [==============================] - 308s 978ms/step - loss: 1375.0880 - val_loss: 1100.8086
Epoch 4/10
315/315 [==============================] - 335s 1s/step - loss: 1350.0170 - val_loss: 1033.0400
Epoch 5/10
315/315 [==============================] - 323s 1s/step - loss: 1327.3416 - val_loss: 979.1115
Epoch 6/10
315/315 [==============================] - 324s 1s/step - loss: 1289.3246 - val_loss: 986.2346
Epoch 7/10
315/315 [==============================] - 318s 1s/step - loss: 1236.3046 - val_loss: 1002.6344
Epoch 8/10
315/315 [==============================] - 313s 992ms/step - loss: 1220.2981 - val_loss: 969.2998
Epoch 9/10
315/315 [==============================] - 312s 992ms/step - loss: 1193.2346 - val_loss: 944.8309
Epoch 10/10
315/315 [==============================] - 317s 1s/step - loss: 1185.6833 - val_loss: 1043.0969

          loss     val_loss
0  3675.466064  1099.001831
1  1412.858154  1079.099365
2  1367.061279  1100.808594
3  1348.074951  1033.040039
4  1304.964722   979.111511
5  1267.620605   986.234558
6  1243.234253  1002.634399
7  1208.138550   969.299805
8  1191.492432   944.830872
9  1184.067261  1043.096924

Wall time: 53min 7s

In [9]:
model = tf.keras.Sequential()

    # add first convolution layer to the model
model.add(tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_last',
    name='conv_1',
    activation='relu'))


    # add a max pooling layer with pool size (2,2) and strides of 2
    # (this will reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    name='pool_1'))


    # add second convolutional layer
model.add(tf.keras.layers.Conv2D(
    filters=64,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    name='conv_2',
    activation='relu'))

    # add second max pooling layer with pool size (2,2) and strides of 2
    # (this will further reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2), name='pool_2')
)


    # add a fully connected layer (need to flatten the output of the previous layers first)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(
    units=1024,
    name='fc_1',
    activation='relu'))

    # add dropout layer
model.add(tf.keras.layers.Dropout(
    rate=0.5))

    # add the last fully connected layer
    # this last layer sets the activation function to "None" in order to output the logits
    # note that passing activation = "sigmoid" will return class memembership probabilities but
    # in TensorFlow logits are prefered for numerical stability
    # set units=1 to get a single output unit (remember it's a binary classification problem)
model.add(tf.keras.layers.Dense(
    units=40000,
    name='fc_2',
    activation='linear'))

model.add(tf.keras.layers.Reshape((200, 200)))
    # build model and print summary
tf.random.set_seed(1)
model.build(input_shape=(None, 200, 200, 3))
model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='mse')
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv_1 (Conv2D)              (None, 200, 200, 32)      896
_________________________________________________________________
pool_1 (MaxPooling2D)        (None, 100, 100, 32)      0
_________________________________________________________________
conv_2 (Conv2D)              (None, 100, 100, 64)      18496
_________________________________________________________________
pool_2 (MaxPooling2D)        (None, 50, 50, 64)        0
_________________________________________________________________
flatten_3 (Flatten)          (None, 160000)            0
_________________________________________________________________
fc_1 (Dense)                 (None, 1024)              163841024
_________________________________________________________________
dropout_3 (Dropout)          (None, 1024)              0
_________________________________________________________________
fc_2 (Dense)                 (None, 40000)             41000000
_________________________________________________________________
reshape_3 (Reshape)          (None, 200, 200)          0
=================================================================
Total params: 204,860,416
Trainable params: 204,860,416
Non-trainable params: 0
_________________________________________________________________

In [10]:
%%time

history = model.fit(
  x = x_train,
  y = y_train,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 10,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
315/315 [==============================] - 326s 1s/step - loss: 2010.6417 - val_loss: 1021.0041
Epoch 2/10
315/315 [==============================] - 325s 1s/step - loss: 1228.1405 - val_loss: 941.9173
Epoch 3/10
315/315 [==============================] - 323s 1s/step - loss: 1183.9600 - val_loss: 960.8654
Epoch 4/10
315/315 [==============================] - 322s 1s/step - loss: 1150.4912 - val_loss: 906.6049
Epoch 5/10
315/315 [==============================] - 323s 1s/step - loss: 1138.2317 - val_loss: 901.9115
Epoch 6/10
315/315 [==============================] - 319s 1s/step - loss: 1131.9276 - val_loss: 886.8053
Epoch 7/10
315/315 [==============================] - 321s 1s/step - loss: 1102.9690 - val_loss: 874.6117
Epoch 8/10
315/315 [==============================] - 323s 1s/step - loss: 1114.0024 - val_loss: 936.2815
Epoch 9/10
315/315 [==============================] - 318s 1s/step - loss: 1107.5866 - val_loss: 885.6168
Epoch 10/10
315/315 [==============================] - 320s 1s/step - loss: 1108.1748 - val_loss: 872.7408

          loss     val_loss
0  1452.567139  1021.004089
1  1215.608398   941.917297
2  1175.481689   960.865417
3  1147.183228   906.604919
4  1134.491211   901.911499
5  1122.947266   886.805298
6  1108.463257   874.611694
7  1111.244385   936.281494
8  1104.099854   885.616760
9  1105.214355   872.740784

Wall time: 53min 50s

In [13]:
model = tf.keras.Sequential()

    # add first convolution layer to the model
model.add(tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_last',
    name='conv_1',
    activation='relu'))


    # add a max pooling layer with pool size (2,2) and strides of 2
    # (this will reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    name='pool_1'))


    # add second convolutional layer
model.add(tf.keras.layers.Conv2D(
    filters=64,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    name='conv_2',
    activation='relu'))

    # add second max pooling layer with pool size (2,2) and strides of 2
    # (this will further reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2), name='pool_2')
)


    # add a fully connected layer (need to flatten the output of the previous layers first)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(
    units=1024,
    name='fc_1',
    activation='relu'))

model.add(tf.keras.layers.Dense(
    units=40000,
    name='fc_2',
    activation='linear'))

model.add(tf.keras.layers.Reshape((200, 200)))
    # build model and print summary
tf.random.set_seed(1)
model.build(input_shape=(None, 200, 200, 3))
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate = 0.01),
              loss='mse')
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv_1 (Conv2D)              (None, 200, 200, 32)      896
_________________________________________________________________
pool_1 (MaxPooling2D)        (None, 100, 100, 32)      0
_________________________________________________________________
conv_2 (Conv2D)              (None, 100, 100, 64)      18496
_________________________________________________________________
pool_2 (MaxPooling2D)        (None, 50, 50, 64)        0
_________________________________________________________________
flatten_5 (Flatten)          (None, 160000)            0
_________________________________________________________________
fc_1 (Dense)                 (None, 1024)              163841024
_________________________________________________________________
fc_2 (Dense)                 (None, 40000)             41000000
_________________________________________________________________
reshape_5 (Reshape)          (None, 200, 200)          0
=================================================================
Total params: 204,860,416
Trainable params: 204,860,416
Non-trainable params: 0
_________________________________________________________________

In [14]:
%%time

history = model.fit(
  x = x_train,
  y = y_train,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 10,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
315/315 [==============================] - 369s 1s/step - loss: 60397.6746 - val_loss: 1466.7728
Epoch 2/10
315/315 [==============================] - 333s 1s/step - loss: 1549.0467 - val_loss: 1463.8707
Epoch 3/10
315/315 [==============================] - 327s 1s/step - loss: 1549.4591 - val_loss: 1461.4596
Epoch 4/10
315/315 [==============================] - 320s 1s/step - loss: 1549.6976 - val_loss: 1460.2429
Epoch 5/10
315/315 [==============================] - 331s 1s/step - loss: 1553.4993 - val_loss: 1461.0597
Epoch 6/10
315/315 [==============================] - 323s 1s/step - loss: 1558.3745 - val_loss: 1461.2578
Epoch 7/10
315/315 [==============================] - 325s 1s/step - loss: 1534.4352 - val_loss: 1462.9283
Epoch 8/10
315/315 [==============================] - 323s 1s/step - loss: 1553.5062 - val_loss: 1462.6196
Epoch 9/10
315/315 [==============================] - 328s 1s/step - loss: 1540.2041 - val_loss: 1464.1658
Epoch 10/10
315/315 [==============================] - 381s 1s/step - loss: 1553.7149 - val_loss: 1461.4508

           loss     val_loss
0  12814.041016  1466.772827
1   1546.192749  1463.870728
2   1546.960205  1461.459595
3   1546.488281  1460.242920
4   1546.379883  1461.059692
5   1546.418701  1461.257812
6   1545.837158  1462.928345
7   1546.144165  1462.619629
8   1546.721558  1464.165771
9   1546.583862  1461.450806

Wall time: 56min 3s

In [27]:
model = tf.keras.Sequential()

    # add first convolution layer to the model
model.add(tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_last',
    name='conv_1',
    activation='relu'))


    # add a max pooling layer with pool size (2,2) and strides of 2
    # (this will reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    name='pool_1'))


    # add second convolutional layer
model.add(tf.keras.layers.Conv2D(
    filters=64,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    name='conv_2',
    activation='relu'))

    # add second max pooling layer with pool size (2,2) and strides of 2
    # (this will further reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2), name='pool_2')
)


    # add a fully connected layer (need to flatten the output of the previous layers first)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(
    units=1024,
    name='fc_1',
    activation='relu'))

    # add dropout layer
model.add(tf.keras.layers.Dropout(
    rate=0.5))

    # add the last fully connected layer
    # this last layer sets the activation function to "None" in order to output the logits
    # note that passing activation = "sigmoid" will return class memembership probabilities but
    # in TensorFlow logits are prefered for numerical stability
    # set units=1 to get a single output unit (remember it's a binary classification problem)
model.add(tf.keras.layers.Dense(
    units=94640,
    name='fc_2',
    activation='linear'))

model.add(tf.keras.layers.Reshape((338, 280)))
    # build model and print summary
tf.random.set_seed(1)
model.build(input_shape=(None, 338, 280, 3))
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate = 0.001),
              loss='mse')
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv_1 (Conv2D)              (None, 338, 280, 32)      896
_________________________________________________________________
pool_1 (MaxPooling2D)        (None, 169, 140, 32)      0
_________________________________________________________________
conv_2 (Conv2D)              (None, 169, 140, 64)      18496
_________________________________________________________________
pool_2 (MaxPooling2D)        (None, 84, 70, 64)        0
_________________________________________________________________
flatten_9 (Flatten)          (None, 376320)            0
_________________________________________________________________
fc_1 (Dense)                 (None, 1024)              385352704
_________________________________________________________________
dropout_7 (Dropout)          (None, 1024)              0
_________________________________________________________________
fc_2 (Dense)                 (None, 94640)             97006000
_________________________________________________________________
reshape_9 (Reshape)          (None, 338, 280)          0
=================================================================
Total params: 482,378,096
Trainable params: 482,378,096
Non-trainable params: 0
_________________________________________________________________

In [21]:
x_train_all = np.load('207_data/saved_data/x_train_3500_balanced.npy')
y_train_all = np.load('207_data/saved_data/y_train_3500_balanced.npy')

In [24]:
x_train_all.shape

(3500, 338, 280, 3)

In [25]:
model

In [28]:
%%time

history = model.fit(
  x = x_train_all,
  y = y_train_all,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 10,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
315/315 [==============================] - 777s 2s/step - loss: 1639.2549 - val_loss: 115.8640
Epoch 2/10
315/315 [==============================] - 745s 2s/step - loss: 214.0420 - val_loss: 107.4963
Epoch 3/10
315/315 [==============================] - 737s 2s/step - loss: 214.6660 - val_loss: 111.8230
Epoch 4/10
315/315 [==============================] - 735s 2s/step - loss: 200.2380 - val_loss: 120.1033
Epoch 5/10
315/315 [==============================] - 734s 2s/step - loss: 199.5248 - val_loss: 101.7247
Epoch 6/10
315/315 [==============================] - 745s 2s/step - loss: 192.9023 - val_loss: 115.5552
Epoch 7/10
315/315 [==============================] - 738s 2s/step - loss: 193.5474 - val_loss: 101.7036
Epoch 8/10
315/315 [==============================] - 735s 2s/step - loss: 190.1989 - val_loss: 110.8516
Epoch 9/10
315/315 [==============================] - 758s 2s/step - loss: 186.2922 - val_loss: 101.3682
Epoch 10/10
315/315 [==============================] - 773s 2s/step - loss: 181.6427 - val_loss: 105.6952

         loss    val_loss
0  515.026245  115.863960
1  214.482956  107.496284
2  210.471069  111.823021
3  200.753311  120.103256
4  194.912582  101.724655
5  191.382980  115.555244
6  193.540710  101.703613
7  190.444855  110.851585
8  187.637604  101.368217
9  182.831573  105.695160

Wall time: 2h 4min 47s

In [30]:
%%time

tf.random.set_seed(1)
history = model.fit(
  x = x_train_all,
  y = y_train_all,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 50,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
63/63 [==============================] - 369s 5s/step - loss: 173.2734 - val_loss: 102.0813
Epoch 2/10
63/63 [==============================] - 342s 5s/step - loss: 173.5376 - val_loss: 100.8725
Epoch 3/10
63/63 [==============================] - 336s 5s/step - loss: 171.1082 - val_loss: 97.1414
Epoch 4/10
63/63 [==============================] - 331s 5s/step - loss: 171.8325 - val_loss: 100.5519
Epoch 5/10
63/63 [==============================] - 333s 5s/step - loss: 171.6899 - val_loss: 97.7301
Epoch 6/10
63/63 [==============================] - 329s 5s/step - loss: 171.4943 - val_loss: 104.1250
Epoch 7/10
63/63 [==============================] - 329s 5s/step - loss: 169.0481 - val_loss: 101.5709
Epoch 8/10
63/63 [==============================] - 329s 5s/step - loss: 171.1443 - val_loss: 100.4202
Epoch 9/10
63/63 [==============================] - 333s 5s/step - loss: 169.7829 - val_loss: 99.9417
Epoch 10/10
63/63 [==============================] - 325s 5s/step - loss: 170.5586 - val_loss: 98.4917

         loss    val_loss
0  173.273376  102.081261
1  173.537598  100.872513
2  171.108215   97.141380
3  171.832474  100.551910
4  171.689865   97.730103
5  171.494293  104.124992
6  169.048141  101.570946
7  171.144333  100.420235
8  169.782898   99.941696
9  170.558624   98.491684

Wall time: 56min 21s

In [31]:
%%time

tf.random.set_seed(1)
history = model.fit(
  x = x_train_all,
  y = y_train_all,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 100,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
32/32 [==============================] - 305s 9s/step - loss: 169.8244 - val_loss: 97.9753
Epoch 2/10
32/32 [==============================] - 291s 9s/step - loss: 167.3924 - val_loss: 99.9250
Epoch 3/10
32/32 [==============================] - 287s 9s/step - loss: 165.5441 - val_loss: 98.0632
Epoch 4/10
32/32 [==============================] - 292s 9s/step - loss: 170.2861 - val_loss: 96.8827
Epoch 5/10
32/32 [==============================] - 282s 9s/step - loss: 170.0699 - val_loss: 101.1447
Epoch 6/10
32/32 [==============================] - 296s 9s/step - loss: 168.1674 - val_loss: 99.1832
Epoch 7/10
32/32 [==============================] - 297s 9s/step - loss: 164.1123 - val_loss: 99.0871
Epoch 8/10
32/32 [==============================] - 293s 9s/step - loss: 165.2750 - val_loss: 97.8473
Epoch 9/10
32/32 [==============================] - 300s 9s/step - loss: 163.1766 - val_loss: 97.8464
Epoch 10/10
32/32 [==============================] - 289s 9s/step - loss: 162.4774 - val_loss: 96.3174

         loss    val_loss
0  169.824417   97.975311
1  167.392380   99.925026
2  165.544083   98.063240
3  170.286118   96.882675
4  170.069916  101.144745
5  168.167374   99.183235
6  164.112274   99.087135
7  165.275009   97.847313
8  163.176575   97.846397
9  162.477432   96.317368

Wall time: 49min 16s

In [33]:
%%time

tf.random.set_seed(1)
history = model.fit(
  x = x_train_all,
  y = y_train_all,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 30,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
105/105 [==============================] - 426s 4s/step - loss: 169.1322 - val_loss: 100.2568
Epoch 2/10
105/105 [==============================] - 413s 4s/step - loss: 168.4216 - val_loss: 96.9621
Epoch 3/10
105/105 [==============================] - 408s 4s/step - loss: 168.8472 - val_loss: 102.1964
Epoch 4/10
105/105 [==============================] - 409s 4s/step - loss: 168.6130 - val_loss: 97.8219
Epoch 5/10
105/105 [==============================] - 403s 4s/step - loss: 169.0005 - val_loss: 94.5929
Epoch 6/10
105/105 [==============================] - 404s 4s/step - loss: 168.7616 - val_loss: 101.3169
Epoch 7/10
105/105 [==============================] - 406s 4s/step - loss: 166.4487 - val_loss: 97.3296
Epoch 8/10
105/105 [==============================] - 401s 4s/step - loss: 168.7637 - val_loss: 98.0702
Epoch 9/10
105/105 [==============================] - 409s 4s/step - loss: 168.7750 - val_loss: 97.1408
Epoch 10/10
105/105 [==============================] - 399s 4s/step - loss: 167.4610 - val_loss: 97.0932

         loss    val_loss
0  169.132187  100.256828
1  168.421631   96.962074
2  168.847244  102.196419
3  168.612961   97.821930
4  169.000519   94.592926
5  168.761566  101.316872
6  166.448654   97.329628
7  168.763672   98.070213
8  168.775024   97.140770
9  167.461044   97.093224

Wall time: 1h 8min 12s

In [34]:
model = tf.keras.Sequential()

    # add first convolution layer to the model
model.add(tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_last',
    name='conv_1',
    activation='relu'))


    # add a max pooling layer with pool size (2,2) and strides of 2
    # (this will reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    name='pool_1'))


    # add second convolutional layer
model.add(tf.keras.layers.Conv2D(
    filters=64,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    name='conv_2',
    activation='relu'))

    # add second max pooling layer with pool size (2,2) and strides of 2
    # (this will further reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2), name='pool_2')
)


    # add a fully connected layer (need to flatten the output of the previous layers first)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(
    units=1024,
    name='fc_1',
    activation='relu'))

    # add dropout layer
model.add(tf.keras.layers.Dropout(
    rate=0.5))

    # add the last fully connected layer
    # this last layer sets the activation function to "None" in order to output the logits
    # note that passing activation = "sigmoid" will return class memembership probabilities but
    # in TensorFlow logits are prefered for numerical stability
    # set units=1 to get a single output unit (remember it's a binary classification problem)
model.add(tf.keras.layers.Dense(
    units=94640,
    name='fc_2',
    activation='linear'))

model.add(tf.keras.layers.Reshape((338, 280)))
    # build model and print summary
tf.random.set_seed(1)
model.build(input_shape=(None, 338, 280, 3))
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate = 0.001),
              loss='mse')
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv_1 (Conv2D)              (None, 338, 280, 32)      896
_________________________________________________________________
pool_1 (MaxPooling2D)        (None, 169, 140, 32)      0
_________________________________________________________________
conv_2 (Conv2D)              (None, 169, 140, 64)      18496
_________________________________________________________________
pool_2 (MaxPooling2D)        (None, 84, 70, 64)        0
_________________________________________________________________
flatten_10 (Flatten)         (None, 376320)            0
_________________________________________________________________
fc_1 (Dense)                 (None, 1024)              385352704
_________________________________________________________________
dropout_8 (Dropout)          (None, 1024)              0
_________________________________________________________________
fc_2 (Dense)                 (None, 94640)             97006000
_________________________________________________________________
reshape_10 (Reshape)         (None, 338, 280)          0
=================================================================
Total params: 482,378,096
Trainable params: 482,378,096
Non-trainable params: 0
_________________________________________________________________

In [35]:
%%time

tf.random.set_seed(1)
history = model.fit(
  x = x_train_all,
  y = y_train_all,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 30,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
105/105 [==============================] - 317s 3s/step - loss: 9064.1683 - val_loss: 1290.9194
Epoch 2/10
105/105 [==============================] - 312s 3s/step - loss: 1417.8582 - val_loss: 1313.4766
Epoch 3/10
105/105 [==============================] - 307s 3s/step - loss: 1540.7936 - val_loss: 1313.6370
Epoch 4/10
105/105 [==============================] - 304s 3s/step - loss: 1409.3319 - val_loss: 1313.6293
Epoch 5/10
105/105 [==============================] - 304s 3s/step - loss: 1411.4952 - val_loss: 1313.3704
Epoch 6/10
105/105 [==============================] - 300s 3s/step - loss: 1418.6622 - val_loss: 1313.6228
Epoch 7/10
105/105 [==============================] - 298s 3s/step - loss: 1387.4142 - val_loss: 1313.6176
Epoch 8/10
105/105 [==============================] - 301s 3s/step - loss: 1413.6796 - val_loss: 1313.6119
Epoch 9/10
105/105 [==============================] - 300s 3s/step - loss: 1395.6723 - val_loss: 1313.6060
Epoch 10/10
105/105 [==============================] - 299s 3s/step - loss: 1408.1070 - val_loss: 1313.5990

          loss     val_loss
0  4878.887207  1290.919434
1  1405.037598  1313.476562
2  1489.739014  1313.636963
3  1400.907104  1313.629272
4  1400.854736  1313.370361
5  1405.910278  1313.622803
6  1400.893433  1313.617554
7  1400.887939  1313.611938
8  1400.881592  1313.605957
9  1400.875244  1313.598999

Wall time: 51min 6s

In [36]:
model = tf.keras.Sequential()

    # add first convolution layer to the model
model.add(tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    data_format='channels_last',
    name='conv_1',
    activation='relu'))


    # add a max pooling layer with pool size (2,2) and strides of 2
    # (this will reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    name='pool_1'))


    # add second convolutional layer
model.add(tf.keras.layers.Conv2D(
    filters=64,
    kernel_size=(3, 3),
    strides=(1, 1),
    padding='same',
    name='conv_2',
    activation='relu'))

    # add second max pooling layer with pool size (2,2) and strides of 2
    # (this will further reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2), name='pool_2')
)


    # add a fully connected layer (need to flatten the output of the previous layers first)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(
    units=1024,
    name='fc_1',
    activation='relu'))

    # add dropout layer
model.add(tf.keras.layers.Dropout(
    rate=0.5))

    # add the last fully connected layer
    # this last layer sets the activation function to "None" in order to output the logits
    # note that passing activation = "sigmoid" will return class memembership probabilities but
    # in TensorFlow logits are prefered for numerical stability
    # set units=1 to get a single output unit (remember it's a binary classification problem)
model.add(tf.keras.layers.Dense(
    units=94640,
    name='fc_2',
    activation='linear'))

model.add(tf.keras.layers.Reshape((338, 280)))
    # build model and print summary
tf.random.set_seed(1)
model.build(input_shape=(None, 338, 280, 3))
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate = 0.0001),
              loss='mse')
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv_1 (Conv2D)              (None, 338, 280, 32)      896
_________________________________________________________________
pool_1 (MaxPooling2D)        (None, 169, 140, 32)      0
_________________________________________________________________
conv_2 (Conv2D)              (None, 169, 140, 64)      18496
_________________________________________________________________
pool_2 (MaxPooling2D)        (None, 84, 70, 64)        0
_________________________________________________________________
flatten_11 (Flatten)         (None, 376320)            0
_________________________________________________________________
fc_1 (Dense)                 (None, 1024)              385352704
_________________________________________________________________
dropout_9 (Dropout)          (None, 1024)              0
_________________________________________________________________
fc_2 (Dense)                 (None, 94640)             97006000
_________________________________________________________________
reshape_11 (Reshape)         (None, 338, 280)          0
=================================================================
Total params: 482,378,096
Trainable params: 482,378,096
Non-trainable params: 0
_________________________________________________________________

In [37]:
%%time

tf.random.set_seed(1)
history = model.fit(
  x = x_train_all,
  y = y_train_all,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 30,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
105/105 [==============================] - 336s 3s/step - loss: 1283.5202 - val_loss: 276.7500
Epoch 2/10
105/105 [==============================] - 325s 3s/step - loss: 453.6837 - val_loss: 281.2179
Epoch 3/10
105/105 [==============================] - 309s 3s/step - loss: 359.9318 - val_loss: 173.5452
Epoch 4/10
105/105 [==============================] - 310s 3s/step - loss: 309.3013 - val_loss: 188.6879
Epoch 5/10
105/105 [==============================] - 308s 3s/step - loss: 294.1446 - val_loss: 176.5627
Epoch 6/10
105/105 [==============================] - 307s 3s/step - loss: 281.5478 - val_loss: 171.6299
Epoch 7/10
105/105 [==============================] - 304s 3s/step - loss: 271.9933 - val_loss: 173.9882
Epoch 8/10
105/105 [==============================] - 302s 3s/step - loss: 261.1520 - val_loss: 167.0740
Epoch 9/10
105/105 [==============================] - 309s 3s/step - loss: 256.1553 - val_loss: 164.6430
Epoch 10/10
105/105 [==============================] - 304s 3s/step - loss: 247.8134 - val_loss: 159.6889

          loss    val_loss
0  1047.373779  276.749969
1   418.430328  281.217865
2   345.011536  173.545227
3   307.447052  188.687897
4   289.588623  176.562653
5   277.912811  171.629913
6   269.229797  173.988220
7   260.289551  167.073990
8   254.084167  164.642990
9   246.488983  159.688904

Wall time: 52min 20s

In [38]:
model = tf.keras.Sequential()

    # add first convolution layer to the model
model.add(tf.keras.layers.Conv2D(
    filters=32,
    kernel_size=(5, 5),
    strides=(1, 1),
    padding='same',
    data_format='channels_last',
    name='conv_1',
    activation='relu'))


    # add a max pooling layer with pool size (2,2) and strides of 2
    # (this will reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2),
    name='pool_1'))


    # add second convolutional layer
model.add(tf.keras.layers.Conv2D(
    filters=64,
    kernel_size=(5, 5),
    strides=(1, 1),
    padding='same',
    name='conv_2',
    activation='relu'))

    # add second max pooling layer with pool size (2,2) and strides of 2
    # (this will further reduce the spatial dimensions by half)
model.add(tf.keras.layers.MaxPool2D(
    pool_size=(2, 2), name='pool_2')
)


    # add a fully connected layer (need to flatten the output of the previous layers first)
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(
    units=1024,
    name='fc_1',
    activation='relu'))

    # add dropout layer
model.add(tf.keras.layers.Dropout(
    rate=0.5))

    # add the last fully connected layer
    # this last layer sets the activation function to "None" in order to output the logits
    # note that passing activation = "sigmoid" will return class memembership probabilities but
    # in TensorFlow logits are prefered for numerical stability
    # set units=1 to get a single output unit (remember it's a binary classification problem)
model.add(tf.keras.layers.Dense(
    units=94640,
    name='fc_2',
    activation='linear'))

model.add(tf.keras.layers.Reshape((338, 280)))
    # build model and print summary
tf.random.set_seed(1)
model.build(input_shape=(None, 338, 280, 3))
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate = 0.001),
              loss='mse')
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv_1 (Conv2D)              (None, 338, 280, 32)      2432
_________________________________________________________________
pool_1 (MaxPooling2D)        (None, 169, 140, 32)      0
_________________________________________________________________
conv_2 (Conv2D)              (None, 169, 140, 64)      51264
_________________________________________________________________
pool_2 (MaxPooling2D)        (None, 84, 70, 64)        0
_________________________________________________________________
flatten_12 (Flatten)         (None, 376320)            0
_________________________________________________________________
fc_1 (Dense)                 (None, 1024)              385352704
_________________________________________________________________
dropout_10 (Dropout)         (None, 1024)              0
_________________________________________________________________
fc_2 (Dense)                 (None, 94640)             97006000
_________________________________________________________________
reshape_12 (Reshape)         (None, 338, 280)          0
=================================================================
Total params: 482,412,400
Trainable params: 482,412,400
Non-trainable params: 0
_________________________________________________________________

In [39]:
%%time

tf.random.set_seed(1)
history = model.fit(
  x = x_train_all,
  y = y_train_all,
  validation_split=0.1,  # use 10% of the examples as a validation set
  batch_size = 30,
  epochs = 10
)

history = pd.DataFrame(history.history)
display(history)

Epoch 1/10
105/105 [==============================] - 576s 5s/step - loss: 1875.4045 - val_loss: 115.3666
Epoch 2/10
105/105 [==============================] - 544s 5s/step - loss: 163.0063 - val_loss: 109.0670
Epoch 3/10
105/105 [==============================] - 536s 5s/step - loss: 153.5932 - val_loss: 102.3341
Epoch 4/10
105/105 [==============================] - 533s 5s/step - loss: 146.8731 - val_loss: 111.8330
Epoch 5/10
105/105 [==============================] - 534s 5s/step - loss: 150.1667 - val_loss: 96.6130
Epoch 6/10
105/105 [==============================] - 521s 5s/step - loss: 142.6432 - val_loss: 93.5254
Epoch 7/10
105/105 [==============================] - 530s 5s/step - loss: 143.8727 - val_loss: 95.0442
Epoch 8/10
105/105 [==============================] - 528s 5s/step - loss: 135.2523 - val_loss: 104.3995
Epoch 9/10
105/105 [==============================] - 539s 5s/step - loss: 126.9534 - val_loss: 93.2389
Epoch 10/10
105/105 [==============================] - 535s 5s/step - loss: 125.7586 - val_loss: 85.6356

         loss    val_loss
0  628.872803  115.366608
1  160.972488  109.067039
2  150.847519  102.334076
3  152.893036  111.833023
4  149.671082   96.612991
5  138.069519   93.525360
6  139.106613   95.044167
7  133.131790  104.399529
8  126.907265   93.238907
9  127.492691   85.635590

Wall time: 1h 30min 6s